version: '3'
services:
  nginx:
    image: nginx:1.25.0
    ports:
      - "127.0.0.1:8000:80"
    volumes:
        - ./php:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
        - ./php:/var/www/html